### ISSUE TITLE
Pictures tab empty

### ISSUE THREAD

**Issue by alexsolans** [spikehip/com.bikeonet.android.dslrbrowser#3]
I installed the app on my android phone. I created a hotspot on the phone and connected my Canon 7D with WTF-E5 to it with MediaServer on. I can view my Canon 7D on the camera tab, but the picture browser tab doesn't show any. I erased all the files on the Compactflash camera memory and shoot some new photos in raw+jpeg but nothing was shown. Can you help me to make this works ????

**Comment by spikehip** [comment]
Sorry, I was not actively monitoring the issues on this. The steps you described should generally work, did work for me with a 7dmk2+E7. 

To the next with a similar issue: please put your phone into debug mode and attach the console logs to the issue.
