### ISSUE TITLE
support nikon camera? and otg connect?

### ISSUE THREAD

**Issue by Restry** [spikehip/com.bikeonet.android.dslrbrowser#6]
hello @spikehip 
We want to develop an app that connects to the camera sync picture to my website. support Canon Nikon . Can you give me a guide?

- is possible to use otg connect camera ?  ios and android
- it's here have any camera sdk ?
- how to connect camera with ios or android devices by programming

thanks a lots

**Comment by spikehip** [comment]
Hi @Restry 
I'm not using any special camera sdk, the apps are based using the DLNA capabilities of the canon wifi transmitters, I don't know if Nikon supports DLNA - when it does, should work as well.

**Comment by Restry** [comment]
hello @spikehip thanks for you reply :)

does this app support OTG cable connection ? because not all canon cameras have wifi .
